# Generated by Django 5.2.4 on 2025-07-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='status',
        ),
    ]
